apiVersion: v1
kind: Service
metadata:
  name: todo-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
